### ISSUE TITLE
Gem?

### ISSUE THREAD

**Issue by lua86** [artemsheludko/galada#5]
This theme looks quite nice, but I think it'd be nicer if people could use it as a gem instead of forking your repository.

**Comment by infominer33** [comment]
I'm gonna pop in to say THANK YOU!!! instead of starting my own issue.

I love it, and the fact that a click of a button "fork" and then a click of another button "publish to master" and I'm live!!!

wooot!

---

While I'm here, I may as well add that you should be able to use this as a remote theme, also:

You need the following in your Gem file:

`gem "jekyll-remote-theme"`

Add the following to your site's _config.yml to let github know you're using it:

```
plugins:
  - jekyll-remote-theme

remote_theme: artemsheludko/galada
```


[that should function](https://github.com/benbalter/jekyll-remote-theme), otherwise, just the same as a gem theme.. although I haven't tested with this repository.

**Comment by artemsheludko** [comment]
@infominer33 
A good idea. I'll think about it. Thank you!
